
#Enable debug logs for Spring
logging.level.org.springframework=DEBUG
#Watch startup time
spring.main.log-startup-info=true
management.endpoints.web.exposure.include=health,info,metrics,beans
#max ? max concurrent request threads
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100