spring.application.name=order-service
#only 2 db connection allowed for testing purpose if 10 request comes 2 will execute and 8 will wait
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=2000
logging.level.com.zaxxer.hikari=DEBUG
#Now your service can process only 5 concurrent requests.
server.tomcat.threads.max=5
