
spring:
  kafka:
    producer:
      acks: all
      retries: 3
      compression-type: snappy
      batch-size: 32768
      linger-ms: 5
    properties:
      enables.idempotence: true
      max.in.flight.requests.per.connection: 5
      transactional.id: payment-tx-producer

  webhook:
    secret: mySuperSecretKey123

